### ISSUE TITLE
Ensuring that safaridriver is ready... Unable to start the server: Operation not permitted

### ISSUE THREAD

**Issue by habib** [CircleCI-Public/macos-orb#24]
## What happened:
Used the Orb but regularly get failures like:
```
./tools/tstest/with-selenium-env.sh npx reftest-driver "--browsers=safari" "--artifactDir=/Users/distiller/src/mn/projects/fullstory/var/reftest" "--testFilter=(cannedsessions/*|dom/*|keep/*|performance/*|privacy/*|recording-safety/*|service-worker/*|svg/*|%)"

No display found. Starting xvfb.
Enabling safaridriver...
Ensuring that safaridriver is ready... Unable to start the server: Operation not permitted
FAILED
Shutting down subprocesses
```

## Expected behavior:
The above step should work, and it does a fair number of times, but not always.

## Additional Information:
N/A

**Comment by BytesGuy** [comment]
@habib Is there a sample project we can use to test this? The sample [browser project](https://github.com/CircleCI-Public/macos-orb/tree/main/sample_browser_project) test in this orb consistently works fine on all images 11.6 and above for me. I can only assume the way the job is configured, or something within the job, is causing this at this point, but we can investigate further.

**Comment by BytesGuy** [comment]
v2.3.1 may resolve this. 

https://github.com/CircleCI-Public/macos-orb/releases/tag/v2.3.1

Closing this issue for now as there is nothing further we can investigate. Please re-open with further details, and a sample project if possible, if this continues to be an issue.
