### ISSUE TITLE
Unable to switch Ruby version using macOS orb

### ISSUE THREAD

**Issue by dhearst** [CircleCI-Public/macos-orb#55]
## Orb version:
2.3.4

## What happened:
In this job:
https://app.circleci.com/projects/github/Enflick/proton-ios/config/?branchName=david%2FSPM-or-bust-based-for-Proton-with-Xcode-14.2&pipelineNumber=3135

We are attempting to use a specific version of Ruby, along with bundler, fastlane and various gems. When we moved to Xcode 14.2 our chruby step started to fail and tech support recommended we switch to using the macOS orb for switching Ruby versions. Ideally we would switch to Ruby 2.6.3 but even with the macOS orb step and what appears to be successful Ruby versions switching , our gem update step still failed with this error:

Your Ruby version is 3.0.5, but your Gemfile specified ~> 2.6.3

Tech support thought that perhaps the problem was caused by Ruby 2.6 being at end-of-life. So, I tried updating Ruby and all of the various tools to current versions. But even with that, the gem update still fails:

#!/bin/bash --login -eo pipefail
bundle install
Your Ruby version is 3.0.5, but your Gemfile specified ~> 3.2.0
 
Exited with code exit status 18
CircleCI received exit code 18

It appears that no matter what I do with the macOS orb, the gem update sees Ruby version 3.0.5.

static:~ distiller$ which ruby
/Users/distiller/.rbenv/shims/ruby
static:~ distiller$ ruby -v
ruby 3.0.5p211 (2022-11-24 revision ba5cf0f7c5) [x86_64-darwin21]
static:~ distiller$ /Users/distiller/.rbenv/shims/ruby -v
ruby 3.0.5p211 (2022-11-24 revision ba5cf0f7c5) [x86_64-darwin21]

## Expected behavior:

Using the macOS orb to with Ruby versions would leave the job configured so that ANY operation sees the configured Ruby version, not the default Ruby version.

**Comment by BytesGuy** [comment]
@dhearst Hi, the issue is here in your config:

```
      - macos/switch-ruby:
          version: "3.2"
```

Ruby 3.2 is not a valid Ruby in the Xcode 14.2 image (it was not available at the time this image was built):

https://circle-macos-docs.s3.amazonaws.com/image-manifest/v10821/manifest.txt

```
Rubies (rbenv): 2.7.7 3.0.5 3.1.3 
Default Ruby: 3.0.5
```

This is therefore falling back to the default Ruby which is 3.0.5 in this image.

We will update this orb to throw an error if the major.minor version of Ruby requested is not installed in the image so that this is made clearer in the future

**Comment by traviswimer** [comment]
I have been able to successfully set a custom version of Ruby by running `rbenv install x.x.x` before running `macos/switch-ruby`.
