### ISSUE TITLE
enable-vnc job fails out of the box

### ISSUE THREAD

**Issue by ajamespro** [CircleCI-Public/macos-orb#58]
## Orb version: 

2.3.4

## Executor: 

macos.m1.large.gen1

## What happened:

`enable-vnc` might be broken on newer versions of MacOS. I think with the new "System Preferences" style changing to "System Settings", and also the "Sharing" options being buried under General is going to need some changes in the AppleScript. Here is the log, this line being the actual error:

`Running AppleScript. Please wait ~20 seconds...293:371: execution error: System Events got an error: Can’t get radio group 1 of group 1 of window "Sharing" of process "System Preferences". Invalid index. (-1719)`

Log:

```log
Creating the user account...2023-04-27 16:00:54.033 sysadminctl[2645:8018] ----------------------------
2023-04-27 16:00:54.033 sysadminctl[2645:8018] No clear text password or interactive option was specified (adduser, change/reset password will not allow user to use FDE) !
2023-04-27 16:00:54.033 sysadminctl[2645:8018] ----------------------------
2023-04-27 16:00:54.081 sysadminctl[2645:8018] Creating user record…
2023-04-27 16:00:54.647 sysadminctl[2645:8018] Assigning UID: 502 GID: 20
2023-04-27 16:00:55.375 sysadminctl[2645:8018] Creating home directory at /Users/vncuser

macOS12+ requires VNC to be enabled via System Preferences...
Granting automation permissions...
Opening System Preferences...
Running AppleScript. Please wait ~20 seconds...293:371: execution error: System Events got an error: Can’t get radio group 1 of group 1 of window "Sharing" of process "System Preferences". Invalid index. (-1719)

Exited with code exit status 1
CircleCI received exit code 1
```

## Expected behavior:

VNC should be enable-able

## Additional Information:

Here is a config to replicate:

```yaml
version: 2.1

orbs:
  macos: circleci/macos@2.3.4

jobs:
  bar:
    macos:
      xcode: 14.2.0
      resource_class: macos.m1.large.gen1
    steps:
      - macos/enable-vnc

workflows:
  foo:
    jobs:
      - bar
```

Visual:

![image](https://user-images.githubusercontent.com/121245612/234925716-ff149a7b-9d32-4541-8caf-0e16e04cf211.png)

**Comment by ajamespro** [comment]
Side note: I attempted to fix it, but have discovered that AppleScript is Satan, and nearly lost my soul in the process. My local environment also has some corporate restrictions that might limiting sharing options and AppleScript itself.

**Comment by zbencz3** [comment]
Same thing happens in my case:
<img width="1580" alt="SystemPref" src="https://github.com/CircleCI-Public/macos-orb/assets/5381246/13bfd402-7e63-4e2e-8024-752c68efdf73">

@BytesGuy would you be able to provide an updated script for Ventura? It seems that the process is called `System Settings` now, instead of `System Preferences`, and the layout is different.

**Comment by BytesGuy** [comment]
This is currently in our backlog, but we do not have an ETA at this time due to other priorities. This is going to require an extensive change to the AppleScript as the new style systems settings is a lot worse to deal with unfortunately.

**Comment by vadimdones** [comment]
Having a similar issue. Any ETA would be appreciated.
