### ISSUE TITLE
Error while using add-safari-permissions in xcode 14.3 environment

### ISSUE THREAD

**Issue by jRichardeau** [CircleCI-Public/macos-orb#59]
## What happened:

When using the `add-safari-permissions` job from this orb in xcode 14.3 environment (and `macos.x86.medium.gen2` resource class) the following error appears

> 207:287: execution error: System Events got an error: Can’t get menu item "Preferences…" of menu 1 of menu bar item "Safari" of menu bar 1 of process "Safari". (-1728)

## Expected behavior:

Safari permissions are enabled

## Additional Information:

This works with xcode 14.2 and `medium` resource class.

Example [workflow](https://app.circleci.com/pipelines/github/wanteeed/extension/7832/workflows/d07cbc95-40ad-4a6a-bc29-0253a3141a6b/jobs/19957/parallel-runs/0?filterBy=FAILED).

Thank you

**Comment by herschel666** [comment]
The menu item isn't named `Preferences` anymore, but `Settings`. Changing this in the script makes it work as expected.

**Comment by BytesGuy** [comment]
@herschel666 can you create a PR to solve the issue? 🙂

**Comment by herschel666** [comment]
@BytesGuy When will v2.3.6 be available in the registry? Latest public version there is v2.3.4.

**Comment by jeremiewtd** [comment]
It works, thank you 🙏
