### ISSUE TITLE
Support add-safari-permissions for Safari (Technology Preview) automation

### ISSUE THREAD

**Issue by merinsTDL** [CircleCI-Public/macos-orb#62]
## Describe Request:
Selenium automation on MacOS executor works with Safari Technology Preview.
However, the orb command add-safari-permissions requires a few tweaks:

1. The osascript that sets permissions leaves Safari instance open. 
Due to current SafariDriver bug (see link below), the browser remains open after the test and throws error if driver.quit() is called. 
The remedy is to kill all Safari and Safari Technology Preview processes before running the next automation session as it will throw an exception due to open browsers. 
Suggested: add `quit app "APPLICATIONNAME"` after the permissions are set to avoid automation error. 

2. The **osascript** steps to enable automation for _Safari Technology Preview_ are slightly different than for _Safari_. 
The application name and the menu navigation steps are different.  
It would require some parameter use different logic in this browser.
Attached snippet that works on Circle CI MacOS executor.
 
## Examples:
Example of working osascript to set permission for Safari Technology Preview. 
`                osascript -e '
                  tell application "System Events"
                    tell application "Safari Technology Preview" to activate
                    delay 15
                    tell process "Safari Technology Preview"
                      set frontmost to true
                      delay 5
                      set settingsLabel to "Preferences…"
                      if menu item "Settings…" of menu 1 of menu bar item "Safari Technology Preview" of menu bar 1 exists then
                        set settingsLabel to "Settings…"
                      end if
                      click menu item settingsLabel of menu 1 of menu bar item "Safari Technology Preview" of menu bar 1
                      delay 5
                      click button "Developer" of toolbar 1 of window 1
                      delay 5
                      tell checkbox "Allow Remote Automation" of group 1 of group 1 of window 1
                        if value is 0 then click it
                        delay 5
                      end tell
                      delay 5
                    end tell
                  end tell'
`

## Supporting Documentation Links:
https://developer.apple.com/forums/thread/76333

**Comment by bjohnso5** [comment]
`v2.5.0` changes the interaction with the underlying image and no longer requires directly toggling UI elements via applescript. Please do reach out if you find that your use case is not satisfied by the new version. Cheers!
