### ISSUE TITLE
add-safari-permissions does not work in xcode 15 environment

### ISSUE THREAD

**Issue by jRichardeau** [CircleCI-Public/macos-orb#68]
## What happened:

The orb execution fails in xcode 15 environment with this error :

```
157:166: execution error: System Events got an error: AppleEvent timed out. (-1712)

Exited with code exit status 1
```

For instance with this [job](https://app.circleci.com/pipelines/github/wanteeed/extension/12473/workflows/a7922eda-fa7d-4e67-8be3-6d5b538c1703/jobs/45463) (tried to rerun).

## Expected behavior:

The execution of the orb works well and grants safari permissions for testing.

## Additional Information:

We tried with `xcode 15.2.0` and `15.3.0` with `resource_class: macos.m1.medium.gen1`

**Comment by jRichardeau** [comment]
Here is more information on the issue, in fact this is because of safari 17 where menu have changed again, as in this [issue](https://github.com/CircleCI-Public/macos-orb/issues/59).

Checkbox `Show Develop menu in menu bar` has been renamed to `Show features for web developers`.

`Allow Remote Automation` has been moved in the settings panel and is not available anymore in the `Develop` menu so we have to click on `Developer Settings…` of the `Develop` menu and then click on checkbox `Allow remote automation`.

Thank you

**Comment by jRichardeau** [comment]
Additionally, "osascript" seems to hang after the command "tell application "System Events"", which is why it times out.

**Comment by vpanta** [comment]
We are seeing the same issue, preventing us from updating to xcode `15.2.0`. We are using Orb v`2.4.1`.

**Comment by vpanta** [comment]
And just to tag, this is the same issue which I raised in CircleCI Discuss this week: https://discuss.circleci.com/t/macos-add-safari-permissions-command-failing-on-xcode-15-2-0/50708
